version: '3'

services:
  server:
    build:
      context: ./serverFile
      dockerfile: DockerFile.server
    volumes:
      - servervol:/serverdata
    networks:
      - mydockernetwork

  client:
    build:
      context: ./clientFile
      dockerfile: DockerFile.client
    volumes:
      - clientvol:/clientdata
    networks:
      - mydockernetwork
    depends_on:
      - server

volumes:
  servervol:
  clientvol:
   
networks:
  mydockernetwork:
    driver: bridge
    
    
